UDP integration
Zewo/Zewo pull request #145
Opened 2016-09-19 22:40 UTC by bosr

# Summary

- [x]  Integrate UDP using git subrepo
- [x] Unit tests
- [x]  fix linux tests (prevent Travis from hanging) with a silly hack

2016-09-19 22:49 UTC, bosr commented
I removed my 'echo' hack as it does not always solve the Travis hanging problem :/

2016-09-20 12:30 UTC, bosr commented
rebased

2016-09-26 06:00 UTC, Danappelxx commented on Modules/UDP/.gitignore
> +# Created by https://www.gitignore.io/api/xcode
could you use the one that SPM generates? https://github.com/Zewo/Zewo/blob/master/.gitignore

2016-09-26 06:00 UTC, Danappelxx commented on Modules/UDP/.travis.yml
> +notifications:
Could you replace this with the updated version such as [here](https://github.com/Zewo/Zewo/blob/master/Modules/Core/.travis.yml)? A few minor differences

2016-09-26 06:01 UTC, Danappelxx commented on Modules/UDP/LICENSE
> +Copyright (c) 2015 Zewo
Could you update this to 2016?

2016-09-26 06:03 UTC, Danappelxx commented on Modules/UDP/Package.swift
> +        .Package(url: "https://github.com/Zewo/Venice.git", majorVersion: 0, minor: 13),
Hmm, we should find a better way to handle this at some point. @paulofaria

2016-09-26 06:03 UTC, Danappelxx commented on Modules/UDP/README.md
> +        .Package(url: "https://github.com/VeniceX/UDP.git", majorVersion: 0, minor: 5)
`minor: 13`

2016-09-26 06:03 UTC, Danappelxx commented on Modules/UDP/README.md
> +        .Package(url: "https://github.com/VeniceX/UDP.git", majorVersion: 0, minor: 5)
Also `Zewo/UDP` :)

2016-09-26 06:04 UTC, Danappelxx commented on Modules/UDP/README.md
> +let udpSocket = try? UDPSocket(ip: IP(port: 5050))
I would just use `try` instead of `try` - makes this cleaner and more understandable.

2016-09-26 06:04 UTC, Danappelxx commented on Modules/UDP/README.md
> +[zewo-badge]: https://img.shields.io/badge/Zewo-0.5-FF7565.svg?style=flat
zewo-0.13

2016-09-26 06:04 UTC, Danappelxx commented on Modules/UDP/README.md
> +[travis-url]: https://travis-ci.org/VeniceX/UDP
Zewo/UDP

2016-09-26 06:05 UTC, Danappelxx requested changes
Just a few things! None of them are code related - that stuff looks good :)

2016-09-26 06:31 UTC, bosr commented
That's some serious proofreading, I'm impressed. I'll fix this very soon.  

Thanks



On September 26, 2016 at 8:05:27 AM, Dan Appel (notifications@github.com(mailto:notifications@github.com)) wrote:

>  
>  
> @Danappelxx requested changes on this pull request.
>  
>  
> Just a few things! None of them are code related - that stuff looks good :)
>  
>  
> In Modules/UDP/.gitignore(https://github.com/Zewo/Zewo/pull/145#pullrequestreview-1478067):
>  
> > @@ -0,0 +1,31 @@ +# Created by https://www.gitignore.io/api/xcode  
>  
> could you use the one that SPM generates? https://github.com/Zewo/Zewo/blob/master/.gitignore
>  
>  
> In Modules/UDP/.travis.yml(https://github.com/Zewo/Zewo/pull/145#pullrequestreview-1478067):
>  
> > @@ -0,0 +1,16 @@ +notifications:  
>  
> Could you replace this with the updated version such as here(https://github.com/Zewo/Zewo/blob/master/Modules/Core/.travis.yml)? A few minor differences
>  
>  
> In Modules/UDP/LICENSE(https://github.com/Zewo/Zewo/pull/145#pullrequestreview-1478067):
>  
> > @@ -0,0 +1,21 @@ +The MIT License (MIT) + +Copyright (c) 2015 Zewo  
>  
> Could you update this to 2016?
>  
>  
> In Modules/UDP/Package.swift(https://github.com/Zewo/Zewo/pull/145#pullrequestreview-1478067):
>  
> > @@ -0,0 +1,13 @@ +import PackageDescription + +let package = Package( + name: "UDP", + dependencies: [ + .Package(url: "https://github.com/Zewo/POSIX.git", majorVersion: 0, minor: 13), + .Package(url: "https://github.com/Zewo/IP.git", majorVersion: 0, minor: 13), + + + // test-only dependencies (not yet available in swiftpm: SE-0019) + .Package(url: "https://github.com/Zewo/Venice.git", majorVersion: 0, minor: 13),  
>  
> Hmm, we should find a better way to handle this at some point. @paulofaria(https://github.com/paulofaria)
>  
>  
> In Modules/UDP/README.md(https://github.com/Zewo/Zewo/pull/145#pullrequestreview-1478067):
>  
> > + +[![Swift][swift-badge]][swift-url] +[![Zewo][zewo-badge]][zewo-url] +[![Platform][platform-badge]][platform-url] +[![License][mit-badge]][mit-url] +[![Slack][slack-badge]][slack-url] +[![Travis][travis-badge]][travis-url] + +## Installation + +```swift +import PackageDescription + +let package = Package( + dependencies: [ + .Package(url: "https://github.com/VeniceX/UDP.git", majorVersion: 0, minor: 5)  
>  
> minor: 13
>  
>  
> In Modules/UDP/README.md(https://github.com/Zewo/Zewo/pull/145#pullrequestreview-1478067):
>  
> > + +[![Swift][swift-badge]][swift-url] +[![Zewo][zewo-badge]][zewo-url] +[![Platform][platform-badge]][platform-url] +[![License][mit-badge]][mit-url] +[![Slack][slack-badge]][slack-url] +[![Travis][travis-badge]][travis-url] + +## Installation + +```swift +import PackageDescription + +let package = Package( + dependencies: [ + .Package(url: "https://github.com/VeniceX/UDP.git", majorVersion: 0, minor: 5)  
>  
> Also Zewo/UDP :)
>  
>  
> In Modules/UDP/README.md(https://github.com/Zewo/Zewo/pull/145#pullrequestreview-1478067):
>  
> > + dependencies: [ + .Package(url: "https://github.com/VeniceX/UDP.git", majorVersion: 0, minor: 5) + ] +) +``` + +## Basic usage + +### Send messages + +Send a message containing "Hello world" from `localhost:5050` to `localhost:5051` + +```swift +import UDP + +let udpSocket = try? UDPSocket(ip: IP(port: 5050))  
>  
> I would just use try instead of try - makes this cleaner and more understandable.
>  
>  
> In Modules/UDP/README.md(https://github.com/Zewo/Zewo/pull/145#pullrequestreview-1478067):
>  
> > + +If you need any help you can join our [Slack](http://slack.zewo.io) and go to the **#help** channel. Or you can create a Github [issue](https://github.com/Zewo/Zewo/issues/new) in our main repository. When stating your issue be sure to add enough details, specify what module is causing the problem and reproduction steps. + +## Community + +[![Slack][slack-image]][slack-url] + +The entire Zewo code base is licensed under MIT. By contributing to Zewo you are contributing to an open and engaged community of brilliant Swift programmers. Join us on [Slack](http://slack.zewo.io) to get to know us! + +## License + +This project is released under the MIT license. See [LICENSE](LICENSE) for details. + +[swift-badge]: https://img.shields.io/badge/Swift-3.0-orange.svg?style=flat +[swift-url]: https://swift.org +[zewo-badge]: https://img.shields.io/badge/Zewo-0.5-FF7565.svg?style=flat  
>  
> zewo-0.13
>  
>  
> In Modules/UDP/README.md(https://github.com/Zewo/Zewo/pull/145#pullrequestreview-1478067):
>  
> > + +This project is released under the MIT license. See [LICENSE](LICENSE) for details. + +[swift-badge]: https://img.shields.io/badge/Swift-3.0-orange.svg?style=flat +[swift-url]: https://swift.org +[zewo-badge]: https://img.shields.io/badge/Zewo-0.5-FF7565.svg?style=flat +[zewo-url]: http://zewo.io +[platform-badge]: https://img.shields.io/badge/Platforms-OS%20X%20--%20Linux-lightgray.svg?style=flat +[platform-url]: https://swift.org +[mit-badge]: https://img.shields.io/badge/License-MIT-blue.svg?style=flat +[mit-url]: https://tldrlegal.com/license/mit-license +[slack-image]: http://s13.postimg.org/ybwy92ktf/Slack.png +[slack-badge]: https://zewo-slackin.herokuapp.com/badge.svg +[slack-url]: http://slack.zewo.io +[travis-badge]: https://travis-ci.org/VeniceX/UDP.svg?branch=master +[travis-url]: https://travis-ci.org/VeniceX/UDP  
>  
> Zewo/UDP
>  
>  
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub(https://github.com/Zewo/Zewo/pull/145#pullrequestreview-1478067), or mute the thread(https://github.com/notifications/unsubscribe-auth/AB2NvBELozb6pbc38aUbWAoWgDTWrBdZks5qt2CngaJpZM4KBCwt).
>  
>  
>  
>  
>

2016-09-26 06:32 UTC, Danappelxx commented
Hahaha, I've done this sort of thing a few times now so the little typos really jump out at me 😃

2016-09-26 11:48 UTC, bosr commented
All done. 

The tests fail partly because of a time tolerance on Ticker Tests that is too strict. See https://github.com/Zewo/Zewo/pull/160

2016-09-28 18:50 UTC, Danappelxx approved these changes

2016-09-28 18:50 UTC, Danappelxx commented
Excellent!

2016-09-28 20:15 UTC, bosr commented
rebased :)

2016-09-29 03:11 UTC, paulofaria commented on Modules/UDP/Package.swift
> +        .Package(url: "https://github.com/Zewo/Venice.git", majorVersion: 0, minor: 13),
I don't think we should do any hacks until SwifPM is fixed.

2016-09-29 03:22 UTC, merged