[ALL] Refactored Core to use DispatchData via Buffer typealias
Zewo/Zewo pull request #150
Opened 2016-09-21 00:57 UTC by robertjpayne

This PR will refactor the entire codebase away from `Data` to `typealias Buffer = DispatchData` for all byte array storage.

There are several reasons for doing this:

- `Data` leaks memory horribly on macOS in Zewo most likely due to lack of autorelease pool
- `Data` is hard to work with in a zero-copy fashion for reading
- `DispatchData` by default tries its hardest to *never* copy the underlying buffers
- `DispatchData` allows more control over when and how memory pointers are created/deallocated

We should see some decent performance gains and less memory usage.

2016-09-21 01:29 UTC, paulofaria commented on Modules/Core/Sources/Core/Buffer/Buffer.swift
> +    return lhs.hexadecimalString() == rhs.hexadecimalString()
maybe we can optimize this? not very important now.. but we could add `// TODO:` so we don't forget

2016-09-21 01:30 UTC, robertjpayne commented on Modules/Core/Sources/Core/Buffer/Buffer.swift
> +    return lhs.hexadecimalString() == rhs.hexadecimalString()
Yea this is mostly for tests but it could definitely be optimised.

2016-09-21 01:31 UTC, paulofaria commented on Modules/Core/Sources/Core/JSON/JSONMapStreamParser.swift
> +        guard chunk.count > 0 else {
we could do:

```swift
guard !chunk.isEmpty else { ... }
```

Swiftlint always nags about this haha.

2016-09-21 01:34 UTC, paulofaria commented on Modules/Core/Sources/Core/JSON/JSONMapStreamParser.swift
> +        }
if the buffer is split this would require a merge wouldn't it?

2016-09-21 01:35 UTC, robertjpayne commented on Modules/Core/Sources/Core/JSON/JSONMapStreamParser.swift
> +        }
@paulofaria nope `subdata` is how you slice w/o doing memcpy on DisatchData

2016-09-21 01:49 UTC, paulofaria commented on Modules/File/Sources/File/File.swift
> +            throw StreamError.closedStream(buffer: Buffer())
this could be `Buffer.empty` right? Maybe find + replace `Buffer()` -> `Buffer.empty`.

2016-09-21 01:49 UTC, robertjpayne commented on Modules/File/Sources/File/File.swift
> +            throw StreamError.closedStream(buffer: Buffer())
@paulofaria Buffer() is a init that just sets to Buffer.empty.

2016-09-22 02:02 UTC, Danappelxx commented on Modules/HTTP/Sources/HTTP/Middleware/BasicAuthMiddleware/BasicAuthMiddleware.swift
>              let decodedData = Data(base64Encoded: tokens[1]),
You missed a few spots here

2016-09-22 02:03 UTC, Danappelxx commented on Modules/HTTP/Sources/HTTP/Parser/RequestParser.swift
> +                requests.append(request)
style: this may be better written inline (`requests.append(Request(...))`)

2016-09-22 02:04 UTC, Danappelxx commented on Modules/Core/Sources/Core/Stream/Stream.swift
> +    func write(from: UnsafeBufferPointer<UInt8>, deadline: Double) throws
I think it may be better to keep this unlabeled (`write(_:)` instead of `write(from:)`

2016-09-22 02:09 UTC, Danappelxx commented on Modules/OpenSSL/Sources/OpenSSL/Random.swift
> +		let pointer = UnsafeMutablePointer<UInt8>.allocate(capacity: size)
got some strange indentation here

2016-09-22 02:10 UTC, Danappelxx requested changes
Bunch of little things, overall this is great! I skimmed over the openssl section because I'm not too familiar with that, though.

2016-09-22 02:10 UTC, Danappelxx commented on Modules/Core/Sources/Core/Buffer/Buffer.swift
> +        self = [UInt8](string.utf8).withUnsafeBufferPointer { Buffer(bytes: $0) }
There are two copies going on here (one for the array initializer, one for the buffer initializer) - not ideal.

Maybe use something like this?

```
self = string.utf8CString.withUnsafeBufferPointer { buffer in
    return buffer.baseAddress!.withMemoryRebound(to: UInt8.self, capacity: buffer.count) { ptr in
        return Buffer(bytes: UnsafeBufferPointer(start: ptr, count: buffer.count))
    }
}
```

2016-09-22 02:10 UTC, Danappelxx commented on Modules/Core/Sources/Core/Buffer/Buffer.swift
> +        return subdata(in: self.startIndex.advanced(by: range.lowerBound)..<self.startIndex.advanced(by: range.upperBound))
should we do bound checks here?

2016-09-22 02:10 UTC, Danappelxx commented on Modules/Core/Sources/Core/Buffer/Buffer.swift
> +// TODO: optimize this
still need optimization? how so?

2016-09-22 02:10 UTC, Danappelxx commented on Modules/Core/Sources/Core/Map/Map.swift
> +    case buffer(Buffer)
I'm not sure if this renaming is necessary, but I'm not against it

2016-09-22 02:10 UTC, Danappelxx commented on Modules/Core/Sources/Core/Stream/Drain.swift
> +
reminder to self: run codebase through a whitespace fixer

2016-09-23 01:43 UTC, robertjpayne commented on Modules/Core/Sources/Core/Buffer/Buffer.swift
> +        return subdata(in: self.startIndex.advanced(by: range.lowerBound)..<self.startIndex.advanced(by: range.upperBound))
I don't think we should -- it's convenience over the start/end index which is going to throw fatal errors anyways.

2016-09-23 01:43 UTC, robertjpayne commented on Modules/Core/Sources/Core/Buffer/Buffer.swift
> +// TODO: optimize this
I've done this now just needed to remove the TODO comment

2016-09-23 01:47 UTC, robertjpayne commented on Modules/OpenSSL/Sources/OpenSSL/Random.swift
> +		let pointer = UnsafeMutablePointer<UInt8>.allocate(capacity: size)
Xcode was using stupid tabs, should be fixed up now

2016-09-23 01:49 UTC, robertjpayne commented on Modules/Core/Sources/Core/Buffer/Buffer.swift
> +        self = [UInt8](string.utf8).withUnsafeBufferPointer { Buffer(bytes: $0) }
This has been implemented now!

2016-09-23 01:50 UTC, robertjpayne commented on Modules/Core/Sources/Core/Map/Map.swift
> +    case buffer(Buffer)
I think it makes sense, we're using buffers not data.

2016-09-23 01:51 UTC, robertjpayne commented on Modules/Core/Sources/Core/Stream/Drain.swift
> +
Not sure what happened, think this is gone now anyways

2016-09-23 01:52 UTC, robertjpayne commented on Modules/Core/Sources/Core/Stream/Stream.swift
> +    func write(from: UnsafeBufferPointer<UInt8>, deadline: Double) throws
Hm true @paulofaria what's your ideal on this? I quite like the `from` label but it could make sense either way

2016-09-23 01:53 UTC, robertjpayne commented on Modules/HTTP/Sources/HTTP/Middleware/BasicAuthMiddleware/BasicAuthMiddleware.swift
>              let decodedData = Data(base64Encoded: tokens[1]),
Needed the base64 methods :(

2016-09-23 02:25 UTC, paulofaria commented on Modules/Core/Sources/Core/Stream/Stream.swift
> +    func write(from: UnsafeBufferPointer<UInt8>, deadline: Double) throws
I think we can go without `from`.

2016-09-23 03:12 UTC, Danappelxx approved these changes

2016-09-23 03:55 UTC, merged