Implement TCP/IP in Swift
Zewo/Zewo pull request #153
Opened 2016-09-22 00:48 UTC by paulofaria

2016-09-22 00:53 UTC, Danappelxx commented on Modules/IP/Sources/IP/IP.swift
> +                    return Int(_OSSwapInt16($0.pointee.sin_port))
you can use `.byteSwapped` instead of `_OSSwapInt16`

2016-09-22 00:54 UTC, Danappelxx commented on Modules/IP/Sources/IP/IP.swift
> +    public var veniceAddress: ipaddr {
Maybe use something like `rawAddress` rather than `veniceAddress`?

2016-09-22 00:56 UTC, Danappelxx commented on Modules/IP/Sources/IP/IP.swift
> +    fileprivate static func ip(address: String, port: Int, mode: IPMode, deadline: Double) throws -> Address {
maybe this should be named `address` instead of `ip`? `let address = IP.address(port:)` makes more sense than `let address = IP.ip(port:)`.

2016-09-22 00:57 UTC, Danappelxx commented on Modules/IP/Sources/IP/IP.swift
> +        return dns_resconf_local(&rc)!
should probably be checking `rc` 😛

2016-09-22 00:58 UTC, Danappelxx commented on Modules/IP/Sources/IP/IP.swift
> +                free(ipv6)
use `ipv6.deallocate(capacity:)` instead of `free`

2016-09-22 00:58 UTC, Danappelxx commented on Modules/IP/Sources/IP/IP.swift
> +                free(ipv6)
(this applies to the rest of the `free` calls here)

2016-09-22 00:59 UTC, paulofaria commented on Modules/IP/Sources/IP/IP.swift
> +    public var veniceAddress: ipaddr {
oh we can delete that! haha it's not needed anymore.

2016-09-22 01:04 UTC, Danappelxx requested changes
Bunch of cleaning to do but overall looks good (though I haven't checked any logistical things)

2016-09-22 01:09 UTC, paulofaria commented on Modules/IP/Sources/IP/IP.swift
> +        return dns_resconf_local(&rc)!
libmill didn't check hahaha. But sure.. I'll make that a throwing func and check

2016-09-22 01:09 UTC, paulofaria commented on Modules/IP/Sources/IP/IP.swift
> +                free(ipv6)
what's the capacity? 1?

2016-09-22 01:10 UTC, paulofaria commented on Modules/IP/Sources/IP/IP.swift
> +                free(ipv6)
do I need to `deinitialize` too?

2016-09-22 01:10 UTC, paulofaria commented on Modules/IP/Sources/IP/IP.swift
> +    fileprivate static func ip(address: String, port: Int, mode: IPMode, deadline: Double) throws -> Address {
done

2016-09-22 01:11 UTC, paulofaria commented on Modules/IP/Sources/IP/IP.swift
> +                    return Int(_OSSwapInt16($0.pointee.sin_port))
cool! that's one thing I'd have to implement differently for Darwin and Linux.

2016-09-22 01:13 UTC, Danappelxx commented on Modules/IP/Sources/IP/IP.swift
> +                free(ipv6)
capacity is 1 in this case (you would have more than one if you have a list).

Deinitialize just sets the memory to zeros iirc, so no you don't need to.

2016-09-22 01:14 UTC, Danappelxx commented on Modules/IP/Sources/IP/IP.swift
> +        return dns_resconf_local(&rc)!
well maybe we shouldn't check either then. people behind libmill know what they're doing haha

2016-09-23 03:05 UTC, robertjpayne commented on Modules/IP/Sources/IP/DNS.swift
> +        if let ipv4 = ipv4 {
This could be defensive

guard ipv4 != nil else {
}

2016-09-23 03:05 UTC, robertjpayne commented on Modules/IP/Sources/IP/DNS.swift
> +        if let ipv6 = ipv6 {
This could also be defensive with a guard if ipv6 != nil

2016-09-23 03:06 UTC, robertjpayne commented on Modules/POSIX/Sources/POSIX/FileDescriptor.swift
> +    if flags == -1 {
This should be defensive

`guard flags != -1` and throw the error in the else statement

2016-09-23 03:07 UTC, robertjpayne commented on Modules/POSIX/Sources/POSIX/Internet.swift
> +        if address.family == .ipv4 {
Does this make more sense as a switch?

2016-09-23 03:08 UTC, robertjpayne commented on Modules/POSIX/Sources/POSIX/Socket.swift
> +    if result != 0 {
make this defensive guard result == 0 else { throw }

2016-09-23 03:08 UTC, robertjpayne commented on Modules/POSIX/Sources/POSIX/Socket.swift
> +        if result != 0 {
make this defensive guard result == 0 else { throw }

2016-09-23 04:46 UTC, robertjpayne commented
@paulofaria I've merged this up with master but a few performance tests shows a 3k req/s regression on my machine.

It's hard to profile properly but my guess is we're just doing too much in our polling loops.

2016-09-23 17:42 UTC, paulofaria commented
The issue is probably the `throws` overhead and the fact that we have work on three different modules now.. `TCP`, `IP`, and `POSIX`.

2017-05-12 03:49 UTC, closed without merging