Move log timestamp to Foundation Date
Zewo/Zewo pull request #184
Opened 2016-10-05 21:41 UTC by JGiola

# Summary

This pull request is aimed to the issue #129 for using Foundation.Date for log timestamps

# Design decisions
I've add a private time formatter shared instance for keeping the initialisation cost low, and set the format template to print hours, minutes, seconds and milliseconds.
I don't know if you prefer additional information on the date or the time is enough.

2016-10-06 10:53 UTC, dreymonde commented
Nice job, thanks! However, I think it is more appropriate to set date format like this:
```swift
formatter.dateFormat = DateFormatter.dateFormat(fromTemplate: "HH:mm:ss.SSS", options: 0, locale: .current)
```
This way, the user's locale will be respected. For example, for me it prints time like this:
> 13:52:19,075

(with comma after 19, not the dot), which is right in my region (Ukraine).

2016-10-06 10:57 UTC, dreymonde reviewed
Also, maybe it's better to put `dateFormatter` inside `Logger` as `fileprivate` property.

2016-10-06 14:24 UTC, JGiola commented
Oh, ok, I've done that at first but then I've gone to do a fixed format.

The dateFormatter property is outside Logger for having it shared across all Logger instances and not create a new one every time a Logger object is created.

I will push the changes when I will be back home.

2016-10-06 16:39 UTC, JGiola commented
While I'm at it, you think I have to change the `HH` part of the template with `jj` to adapt dinamically to 12/24 hour clock?
Or at least is what I can understand from this [documentation](http://www.unicode.org/reports/tr35/tr35-31/tr35-dates.html#Date_Format_Patterns) even if I don't know if you have to add the `a` to add AM/PM...

2016-10-06 23:16 UTC, Danappelxx requested changes
Great PR! Just need to figure out the format and it's good to go.

2016-10-06 23:16 UTC, Danappelxx commented on Modules/Axis/Sources/Axis/Log/Log.swift
> +        let format = DateFormatter.dateFormat(fromTemplate: "HH:mm:ss.SSS", options: 0, locale: .current)
Could we also include the day/month/year and locale here? I think that would be useful. Ideal date IMO: `10/06/16 12:42:10.123 GMT-8`.

Note - I'm not sure if `DateFormatter` supports figuring out whether the month should go before or in-between the day and year (in the US, we have the day in the middle).

I also think we should use the 24-hour system regardless of the locale, so the code you have now (`HH`) is good.

2016-10-07 05:54 UTC, JGiola commented
No problem, for the mont and day I'm sure it can do if you use the enum specifiers, I don't know if it will do the same with the localised template...

2016-10-07 07:17 UTC, JGiola commented
Done, I've even removed the separator from the template because they aren't needed, foundation is figuring out everything by itself.

And yes, the order of year, month and day are based on the locale 👍🏻

2016-10-07 07:34 UTC, Danappelxx commented
Awesome! Just one more thing - could you write a unit test that ensures the formatter spits out the right string? I believe what you say about the unnecessary separators but I'm worried that it might be different on Linux for whatever reason, etc.

2016-10-07 07:34 UTC, Danappelxx approved these changes

2016-10-07 18:24 UTC, JGiola commented
The tests are no problem, but it possible to cheat a bit? 😁
Because the actual lotTimeFormatter is a fileprivate property I can't access directly inside the tests and in addition to that I have to set a fixed sets of locale and time zone to know how the strings would come out and so reset the dateFormat to it.

My idea is to tests on a brand new DateFormatter with a couple of different locale and time zone and two or three different dates to see if the format string without any separator is always equals to something we will know.
Is it ok for you?

2016-10-07 18:26 UTC, Danappelxx commented
If you use `@testable import` you should be able to access the `fileprivate` property. If this does not work, maybe make the formatter public? That could provide other benefits (user customization) anyway. 

I agree that you should use several constant dates with locales and just plug them into the formatter.

2016-10-08 15:42 UTC, JGiola commented
`@testable import`allow only internal properties to be accessible. I've moved the `logTimeFormatter` property to be public so people can changes all the properties as they like.

The tests will check against the en_US and it_IT locales, I have to add another one?

2016-10-09 08:33 UTC, JGiola commented
I'm start to thinking that on Linux the unicode library is parsing the date skeleton template in a totally different way than on macOS.
It seems to completely ignore the forced 24 hour marker and for the Italian locale the two platform don't agree on the coma separator between date and hour...

2016-10-10 12:17 UTC, JGiola commented
Ok, I've spin up an ubuntu 12.04 server and I've found a super weird bug. On Linux if you add anyone of the time zone specifier to the skeleton format will disable the forced 24h format, as soon as you change the skeleton from `yyMMdd HHmmssSSSz` to `yyMMdd HHmmssSSS` the printed hours will revert correctly to the force 24h format.

2016-10-12 20:18 UTC, Danappelxx commented
Interesting... so what you're saying is that removing the z will fix it? Can you try committing that change? If it fixes CI, we can happily merge :)

2016-10-14 18:16 UTC, Danappelxx commented
Oh, so removing Z removes the time zone? That's a shame... @paulofaria @robertjpayne what do you think is the right thing to do here?

2016-10-14 18:25 UTC, paulofaria commented
@JGiola could you please raise a bug at bug.swift.org? I think the formatting itself is secondary in regards to correctness. Timezones should be respected above all. If this means different formatting, I'm fine with that.

2016-10-14 19:04 UTC, JGiola commented
Yeah, I've filed it when I've been able to check what was going on on a Ubuntu server.
If you want to join in and write it down better is here https://bugs.swift.org/browse/SR-2906

2016-10-14 19:05 UTC, JGiola commented
In regard of the pull request what you want me to do? Going back on adding the time zone to the skeleton format and comment out the tests for now? Or leave things as they are now?

2016-11-11 01:58 UTC, merged